version: '3.1'

services:

  client_web:
    build:
      context: .
      dockerfile: client_web.dockerfile
    restart: always
    volumes:
      - ./components:/app/components
      - ./interfaces:/app/interfaces
      - ./pages:/app/pages
      - ./utils:/app/utils
    ports:
      - 3000:3000
