version: '3'
services:
  web_server:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#  web_client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mobile_client
#      - web_server
#    volumes:
#      - client_data:/data/client
#  mobile_client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    volumes:
#      - client_data:/data/client
#  apollo:
#    build:
#      context: ./database
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#    depends_on:
#      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  client_data: