version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    depends_on:
      - apollo
    ports:
      - "8080:8080"
    environment:
      MAIL_FROM: MAIL_FROM
      DISCORD_CLIENT_ID: DISCORD_CLIENT_ID
      DISCORD_CLIENT_SECRET: DISCORD_CLIENT_SECRET
      GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
      GOOGLE_REDIRECT_URI: GOOGLE_REDIRECT_URI
      GOOGLE_OAUTH_URL: GOOGLE_OAUTH_URL
      DISCORD_REDIRECT_URI: DISCORD_REDIRECT_URI
      ENV_NAME: ENV_NAME
      API_PORT: API_PORT
      SEND_GRID_API_KEY: SEND_GRID_API_KEY
      POSTGRES_URL: POSTGRES_URL
      WEATHER_API_KEY: WEATHER_API_KEY
      CLIENT_ID: CLIENT_ID
      CLIENT_SECRET: CLIENT_SECRET
      REDIRECT_URL: REDIRECT_URL
    env_file:
      - .env
    networks:
      - server_network
    links:
      - db:area_database
  client_web:
    build:
      context: ./client/
      dockerfile: client_web.dockerfile
    ports:
      - "8081:8081"
    environment:
      REACT_DISCORD_CLIENT_SECRET: REACT_DISCORD_CLIENT_SECRET
      REACT_APP_DISCORD_CLIENT_ID: REACT_APP_DISCORD_CLIENT_ID
      REACT_APP_DISCORD_REDIRECT_URI: REACT_APP_DISCORD_REDIRECT_URI
      REACT_GITHUB_CLIENT_SECRET: REACT_GITHUB_CLIENT_SECRET
      REACT_APP_GITHUB_CLIENT_ID: REACT_APP_GITHUB_CLIENT_ID
    depends_on:
      - client_mobile
      - server
    volumes:
      - ./client_data:/app/client
  client_mobile:
    build:
      context: ./client/
      dockerfile: client_mobile.dockerfile
    volumes:
      - ./client_data:/app/client
  apollo:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      POSTGRES_URL: POSTGRES_URL
    env_file:
      - .env
    networks:
      - server_network
    depends_on:
      - db
    links:
      - db:area_database
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - server_network
    ports:
      - "5432:5432"
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    restart: always
    environment:
      BOT_TOKEN: BOT_TOKEN
      ENV_NAME: ENV_NAME
      API_PORT: API_PORT
      SEND_GRID_API_KEY: SEND_GRID_API_KEY
      POSTGRES_URL: POSTGRES_URL
      API_URL: API_URL
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/discord-bot/data
    networks:
      - server_network
    depends_on:
      - db
      - server

networks:
  server_network:
    driver: bridge
volumes:
  postgres_data:
  client_data: