version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    depends_on:
      - apollo
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - server_network
    links:
      - db:area_database
  client_web:
    build:
      context: ./client/
      dockerfile: client_web.dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - client_mobile
      - server
    volumes:
      - ./client_data:/app/client
  client_mobile:
    build:
      context: ./client/
      dockerfile: client_mobile.dockerfile
    env_file:
      - .env
    volumes:
      - ./client_data:/app/client
  apollo:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - server_network
    depends_on:
      - db
    links:
      - db:area_database
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - server_network
    ports:
      - "5432:5432"
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/discord-bot/data
    networks:
      - server_network
    depends_on:
      - apollo
      - server
    links:
      - db:area_database

networks:
  server_network:
    driver: bridge
volumes:
  postgres_data:
  client_data: