version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env/.env.dev
    networks:
      - server_network
    links:
      - db:area_database
    command: npx prisma migrate dev --preview-feature --schema=./prisma/schema.prisma
  client_web:
    build:
      context: ./client
      dockerfile: client_web.dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - client_mobile
      - server
    volumes:
      - client_data:/data/client
  client_mobile:
    build:
      context: ./client
      dockerfile: client_mobile.dockerfile
    volumes:
      - client_data:/data/client
  apollo:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./database/.env/.env.dev
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - ./database/.env/.env.dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/data/db
    ports:
      - "5432:5432"
    networks:
      - server_network
networks:
  server_network:
    driver: bridge
volumes:
  postgres_data:
  client_data: