name: Build

on:
  push:
    branches: [ main ]
  delete:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  to_github:
    name: Push content of the current repo on mirror
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_AREA_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_AREA_MIRRORING_KEY }}