name: Build

on:
  push:
    branches: [ main ]
  delete:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ database, server, client_web, client_mobile ]
    steps:
      - uses: actions/checkout@v3
      - name: test image name
        run: echo area_${{ matric.service }}/${{ github.ref_name }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v4
        if: matrix.service == 'database' || matrix.service == 'server'
        with:
          context: ${{ github.workspace }}/${{ matrix.service }}
          file: ${{ github.workspace }}/${{ matrix.service }}/Dockerfile
          tags: area_${{ matrix.service }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - uses: docker/build-push-action@v4
        if: matrix.service == 'client_web' || matrix.service == 'client_mobile'
        with:
          context: ${{ github.workspace }}/client
          file: ${{ github.workspace }}/client/${{ matrix.service }}.dockerfile
          tags: area_${{ matrix.service }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=min

  to_github:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Push content of the current repo on mirror
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_AREA_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_AREA_MIRRORING_KEY }}